### ISSUE TITLE
Crash on Quilt 1.20.1

### ISSUE THREAD

**Issue by Anoaxx** [sf-inc/music_control#47]
[crash-2023-12-08_24.59.09.8339-quilt_loader.txt](https://github.com/sf-inc/music_control/files/13607643/crash-2023-12-08_24.59.09.8339-quilt_loader.txt)

**Comment by charlyb01** [comment]
Hi again! I'm not familiar with Quilt, but anyway your crash report indicates that it's `panorama_screens` that crashed your game. I didn't see anything related to Music Control. Don't hesitate to tell if I missed something

**Comment by Anoaxx** [comment]
i didnt even had that mod in folder ;-;

**Comment by Anoaxx** [comment]
nevermind how to delete issue?

**Comment by charlyb01** [comment]
It seems to be an internal dependency of bedrockify. We can close it if everything's okay for you now

**Comment by Anoaxx** [comment]
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'music_control'!
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:66)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:34)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:64)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:56)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.NoClassDefFoundError: io/github/cottonmc/cotton/gui/GuiDescription
	at com.github.charlyb01.music_control.client.MusicControlClient.onInitializeClient(MusicControlClient.java:36)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$1(Hooks.java:56)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62)
	... 12 more
Caused by: java.lang.ClassNotFoundException: io.github.cottonmc.cotton.gui.GuiDescription
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:175)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:147)
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:239)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 16 more

**Comment by Anoaxx** [comment]
So i have proper crash raport. look!

**Comment by Anoaxx** [comment]
tell me if u need more details from crash raport

**Comment by Anoaxx** [comment]
@charlyb01 Could you delete the "invalid" tag?

**Comment by charlyb01** [comment]
I guess this is another issue then. We can keep this one if you want, but first I'll need more information about your install before removing the invalid tag. I tried loading it on Quilt 1.20.1 with Music Control 1.6.2 and it worked fine. What else did you have? I'd like the proper crash report as you said, not just part of it.

Also, if you could at least reproduce with less mods if you have the same mods than last time, that would be helpful, because I'm not going to check 200+ mods compatibility ^^

**Comment by charlyb01** [comment]
As latest version is not compatible anymore with Quilt, I'm not going to investigate more this issue.
