### ISSUE TITLE
Mc 1.21.3

### ISSUE THREAD

**Issue by FlailoftheLord** [sf-inc/music_control#67]
Mod is not marked as being compatible for 1.21.1-3
It was working on 1.21.1 for me, but the update to 1.21.3 bricked the poor mod.
Leaving the stacktrace here... I'm not sure if or when an update is planned.

Game Version: _1.21.3_
Fabric Loader: _0.16.9_
Mod Version: _1.8.3+1.21_ (latest on modrinth)
Fabric API: _0.107.0+1.21.3_

**Java Stacktrace**:
```err
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 2024-11-06 16:47:47
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'music_control' at 'com.github.charlyb01.music_control.client.MusicControlClient'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at knot//net.minecraft.class_310.<init>(class_310.java:482)
	at knot//net.minecraft.client.main.Main.main(Main.java:248)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NoClassDefFoundError: io/github/cottonmc/cotton/gui/GuiDescription
	at knot//com.github.charlyb01.music_control.client.MusicControlClient.onInitializeClient(MusicControlClient.java:38)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 9 more
Caused by: java.lang.ClassNotFoundException: io.github.cottonmc.cotton.gui.GuiDescription
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 11 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at knot//net.minecraft.class_310.<init>(class_310.java:482)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at knot//net.minecraft.client.main.Main.main(Main.java:248)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

```

**Comment by charlyb01** [comment]
Hi, the crash is expected as the mod has not been updated for 1.21.2-3 yet. The port is planned, but I can't tell you when I'll have the time to do it. This will be available before the end of the year though. I'll let you know when it's done

**Comment by FlailoftheLord** [comment]
Yeah, I figured that was just it. 
From checking the source code, only a few things need to be changed aside from versioning.
`type.getSound().value().id()` in `MusicTrackerMixin.java, MusicCategories.java` and `MusicIdentifier.java`
I forked and modified the code, but when compiling, gradle throws an error about something related to `BiomeKeys`
I'll update if I'm able to figure it out.

**Comment by FlailoftheLord** [comment]
https://github.com/sf-inc/music_control/pull/68

**Comment by FlailoftheLord** [comment]
https://github.com/sf-inc/music_control/pull/68
